# futurisys-ml-deploy/scripts/build_env_from_secrets.yml
# Workflow: crée un fichier .env à partir des GitHub Secrets, exporte les variables
# pour les steps suivants et lance des vérifications / scripts DB.


# futurisys-ml-deploy/scripts/build_env_from_secrets.yml
# Workflow INFRA / SETUP
# Objectif : initialisation ponctuelle de l'environnement et de la base PostgreSQL
# ⚠️ Ce workflow n'est PAS une CI et ne doit PAS être exécuté automatiquement.

name: Setup environment and database (manual)

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for running DB setup (optional)"
        required: false
        default: "Initial setup or schema update"

permissions:
  contents: read

jobs:
  setup-db:
    name: Build .env and setup PostgreSQL schema
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupération du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Installation Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 3️⃣ Installation dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      # 4️⃣ Génération du fichier .env (runtime uniquement)
      - name: Build .env file from GitHub Secrets
        run: |
          echo "## Generated by GitHub Actions - DO NOT COMMIT" > .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "ENVIRONMENT=ci" >> .env
          echo "API_DEBUG=False" >> .env

      # 5️⃣ Export des variables pour les scripts suivants
      - name: Export environment variables
        run: |
          grep -v '^#' .env | sed '/^[[:space:]]*$/d' >> $GITHUB_ENV

      # 6️⃣ Vérification non sensible
      - name: Validate environment
        run: |
          echo "ENVIRONMENT=$ENVIRONMENT"
          echo ".env file created successfully"

      # 7️⃣ Création des tables PostgreSQL (idempotent)
      - name: Create database schema
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python src/data/create_db.py

      # 8️⃣ Résumé final
      - name: Summary
        run: |
          echo "✅ Database setup completed successfully"
          echo "Triggered manually for reason: ${{ github.event.inputs.reason }}"
